# Generated by Django 4.0.6 on 2022-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_categories_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
