# Generated by Django 4.0.6 on 2022-08-10 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_later',
            field=models.ManyToManyField(blank=True, related_name='read_later', to=settings.AUTH_USER_MODEL),
        ),
    ]
